### ISSUE TITLE
Decoding issue ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [CorruptComputer/ProtonDB-Tags#52]
**Describe the bug**
> What isn't working?

The script

> Was this working before a recent update?

Yes. Doesn't know the specific update when this happened.

> What version of Python are you using? (`python --version`)

Python 3.10.7

**Script Output**
```
pm  …/ProtonDB-Tags   main   11:18  python3 ProtonDB-Tags.py --check-native                                                                                                                   
Steam found at: /home/pm/.local/share/Steam/userdata
Found user 0: 150966242   PoorPocketsMcNewHold
Found user 1: 0   (Unknown)
Found user 2: anonymous   (Unknown)
Which user number would you like to open? 0
Selected: /home/pm/.local/share/Steam/userdata/150966242/7/remote/sharedconfig.vdf
Traceback (most recent call last):
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 355, in <module>
    main(ARGUMENTS)
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 225, in main
    cache_manager = CacheManager()
  File "/home/pm/Documents/ProtonDB-Tags/Utils/CacheManager.py", line 57, in __init__
    self._steam_native_cache = json.load(cache_json)
  File "/usr/lib64/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Skipping cache, and/or refreshing the configuration doesn't correct it. Re-creating the sharedconfig.vdf file didn't fixed it either.

**Comment by CorruptComputer** [comment]
Hmm, I'm not exactly sure why that would happen, but I'll look into this issue over the weekend.

If possible could you attach the `~/.cache/ProtonDB-Tags/steamNativeCache.json` so I can take a look at what is happening here? I think that would make this issue easier to debug if I was able to re-create it locally.

**Comment by PoorPocketsMcNewHold** [comment]
Indeed. It works.
I was wondering where the cache was, to manually delete it. Thanks !
